package com.lcwd.uploadservice.service.impl;

import com.lcwd.uploadservice.dto.*;
import com.lcwd.uploadservice.entity.PartSummary;
import com.lcwd.uploadservice.entity.UploadSession;
import com.lcwd.uploadservice.entity.UploadStatus;
import com.lcwd.uploadservice.exceptions.ResourceNotFoundException;
import com.lcwd.uploadservice.repository.UploadSessionRepository;
import com.lcwd.uploadservice.service.StorageService;
import com.lcwd.uploadservice.service.UploadService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.*;

@Service
@RequiredArgsConstructor
public class UploadServiceImpl implements UploadService {
    @Value("${minio.chunk-size}")
    private long chunkSize;

    @Value("${minio.bucket}")
    private String bucketName;

    private final UploadSessionRepository repository;
    private final StorageService storageService;

    @Override
    public InitiateUploadResponse initiateUpload(InitiateUploadRequest request) {
        Optional<UploadSession> existing = repository.findFirstByFingerprintAndStatusIn(
                request.fingerprint(),
                List.of(UploadStatus.INITIATED, UploadStatus.UPLOADING)
        );

        if (existing.isPresent()) {
            UploadSession session = existing.get();
            List<Integer> uploadedParts = storageService
                    .listParts(session.getObjectKey(), session.getS3UploadId())
                    .stream()
                    .map(PartSummary::partNumber)
                    .toList();

            return new InitiateUploadResponse(
                    session.getId(),
                    session.getChunkSize(),
                    session.getTotalParts(),
                    session.getStatus(),
                    uploadedParts
            );
        }

        int totalParts = calculateTotalParts(request.fileSize());

        // id is generated by the entity itself (UploadSession.id defaults to a fresh UUID)
        UploadSession session = UploadSession.builder()
                .fileName(request.fileName())
                .contentType(request.contentType())
                .fileSize(request.fileSize())
                .chunkSize(chunkSize)
                .totalParts(totalParts)
                .fingerprint(request.fingerprint())
                .status(UploadStatus.INITIATED)
                .createdAt(Instant.now())
                .updatedAt(Instant.now())
                .build();

        String objectKey = session.getId() + "/" + request.fileName();
        String s3UploadId = storageService.createMultipartUpload(objectKey, request.contentType());

        session.setObjectKey(objectKey);
        session.setS3UploadId(s3UploadId);

        repository.save(session);

        return new InitiateUploadResponse(
                session.getId(),
                chunkSize,
                totalParts,
                UploadStatus.INITIATED,
                Collections.emptyList()
        );
    }

    @Override
    public UploadStatusResponse getStatus(UUID sessionId) {
        Optional<UploadSession> existing = repository.findById(sessionId);
        if(existing.isPresent()){
            UploadSession session = existing.get();
            List<Integer> uploadedParts = storageService
                    .listParts(session.getObjectKey(), session.getS3UploadId())
                    .stream()
                    .map(PartSummary::partNumber)
                    .toList();
            long bytesUploaded = Math.min(uploadedParts.size() * session.getChunkSize(), session.getFileSize());
            return new UploadStatusResponse(
                    session.getId(),
                    session.getFileName(),
                    session.getFileSize(),
                    session.getChunkSize(),
                    session.getTotalParts(),
                    session.getStatus(),
                    uploadedParts,
                    bytesUploaded
            );
        }

        throw new ResourceNotFoundException("Session with id " + sessionId + " doesn't exist");
    }

    @Override
    public List<PresignedPartResponse> presignParts(UUID sessionId, List<Integer> partNumbers) {
        return List.of();
    }

    @Override
    public CompleteUploadResponse completeUpload(UUID sessionId) {
        return null;
    }

    @Override
    public void abortUpload(UUID sessionId) {

    }

    @Override
    public void cleanupStaleUploads() {

    }

    private int calculateTotalParts(long fileSize) {
        // returns Ceil value
        return Math.toIntExact((fileSize + chunkSize - 1) / chunkSize);
    }
}