package com.lcwd.uploadservice.service.impl;

import com.lcwd.uploadservice.dto.*;
import com.lcwd.uploadservice.entity.PartSummary;
import com.lcwd.uploadservice.entity.UploadSession;
import com.lcwd.uploadservice.entity.UploadStatus;
import com.lcwd.uploadservice.exceptions.ResourceNotFoundException;
import com.lcwd.uploadservice.repository.UploadSessionRepository;
import com.lcwd.uploadservice.service.StorageService;
import com.lcwd.uploadservice.service.TranscodeService;
import com.lcwd.uploadservice.service.UploadService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.stream.IntStream;

@Slf4j
@Service
@RequiredArgsConstructor
public class UploadServiceImpl implements UploadService {
    @Value("${minio.chunk-size}")
    private long chunkSize;

    @Value("${minio.presign-expiry-minutes:15}")
    private long presignExpiryMinutes;

    @Value("${minio.stale-after-hours:24}")
    private long staleAfterHours;


    private final UploadSessionRepository repository;
    private final StorageService storageService;
    private final TranscodeService transcodeService;

    @Override
    public InitiateUploadResponse initiateUpload(InitiateUploadRequest request) {
        Optional<UploadSession> existing = repository.findFirstByFingerprintAndStatusIn(
                request.fingerprint(),
                List.of(UploadStatus.INITIATED, UploadStatus.UPLOADING)
        );

        if (existing.isPresent()) {
            UploadSession session = existing.get();
            List<Integer> uploadedParts = storageService
                    .listParts(session.getObjectKey(), session.getS3UploadId())
                    .stream()
                    .map(PartSummary::partNumber)
                    .toList();

            return new InitiateUploadResponse(
                    session.getId(),
                    session.getChunkSize(),
                    session.getTotalParts(),
                    session.getStatus(),
                    uploadedParts
            );
        }

        int totalParts = calculateTotalParts(request.fileSize());

        // id is generated by the entity itself (UploadSession.id defaults to a fresh UUID)
        UploadSession session = UploadSession.builder()
                .fileName(request.fileName())
                .contentType(request.contentType())
                .fileSize(request.fileSize())
                .chunkSize(chunkSize)
                .totalParts(totalParts)
                .fingerprint(request.fingerprint())
                .status(UploadStatus.INITIATED)
                .createdAt(Instant.now())
                .updatedAt(Instant.now())
                .build();

        String objectKey = session.getId() + "/" + request.fileName();
        String s3UploadId = storageService.createMultipartUpload(objectKey, request.contentType());

        session.setObjectKey(objectKey);
        session.setS3UploadId(s3UploadId);

        repository.save(session);

        return new InitiateUploadResponse(
                session.getId(),
                chunkSize,
                totalParts,
                UploadStatus.INITIATED,
                Collections.emptyList()
        );
    }

    @Override
    public UploadStatusResponse getStatus(UUID sessionId) {
        Optional<UploadSession> existing = repository.findById(sessionId);
        if(existing.isPresent()){
            UploadSession session = existing.get();

            // Once the multipart upload is completed or aborted, its S3 uploadId no longer
            // exists, so listParts would throw. Only ask S3 while the upload is still in
            // progress; otherwise every part is already accounted for.
            List<Integer> uploadedParts;
            long bytesUploaded;
            if (session.getStatus() == UploadStatus.INITIATED || session.getStatus() == UploadStatus.UPLOADING) {
                uploadedParts = storageService
                        .listParts(session.getObjectKey(), session.getS3UploadId())
                        .stream()
                        .map(PartSummary::partNumber)
                        .toList();
                bytesUploaded = Math.min(uploadedParts.size() * session.getChunkSize(), session.getFileSize());
            } else {
                uploadedParts = IntStream.rangeClosed(1, session.getTotalParts()).boxed().toList();
                bytesUploaded = session.getFileSize();
            }

            return new UploadStatusResponse(
                    session.getId(),
                    session.getFileName(),
                    session.getFileSize(),
                    session.getChunkSize(),
                    session.getTotalParts(),
                    session.getStatus(),
                    uploadedParts,
                    bytesUploaded,
                    session.getHlsMasterKey(),
                    session.getTranscodeError()
            );
        }

        throw new ResourceNotFoundException("Session with id " + sessionId + " doesn't exist");
    }

    @Override
    public List<PresignedPartResponse> presignParts(UUID sessionId, List<Integer> partNumbers) {
        UploadSession session = repository.findById(sessionId)
                .orElseThrow(() -> new ResourceNotFoundException("Session with id " + sessionId + " doesn't exist"));

        if (session.getStatus() != UploadStatus.INITIATED && session.getStatus() != UploadStatus.UPLOADING) {
            throw new IllegalStateException("Cannot presign parts for a session in status " + session.getStatus());
        }

        for (Integer partNumber : partNumbers) {
            if (partNumber < 1 || partNumber > session.getTotalParts()) {
                throw new IllegalArgumentException(
                        "Invalid part number " + partNumber + " — must be between 1 and " + session.getTotalParts());
            }
        }

        Duration expiry = Duration.ofMinutes(presignExpiryMinutes);
        Instant expiresAt = Instant.now().plus(expiry);

        List<PresignedPartResponse> responses = partNumbers.stream()
                .map(partNumber -> new PresignedPartResponse(
                        partNumber,
                        storageService.presignUploadPart(session.getObjectKey(), session.getS3UploadId(), partNumber, expiry).toString(),
                        expiresAt
                ))
                .toList();

        if (session.getStatus() == UploadStatus.INITIATED) {
            session.setStatus(UploadStatus.UPLOADING);
            session.setUpdatedAt(Instant.now());
            repository.save(session);
        }

        return responses;
    }

    @Override
    public CompleteUploadResponse completeUpload(UUID sessionId) {
        UploadSession session = repository
                .findById(sessionId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Session with id " + sessionId + " doesn't exist")
                );

        if (session.getStatus() != UploadStatus.INITIATED && session.getStatus() != UploadStatus.UPLOADING) {
            throw new IllegalStateException("Cannot complete a session in status " + session.getStatus());
        }

        // Check if all the parts are uploaded or not
        List<PartSummary> uploadedParts = storageService.listParts(session.getObjectKey(), session.getS3UploadId());
        if(uploadedParts.size() != session.getTotalParts()){
            throw new ResourceNotFoundException("All Parts are not uploaded");
        }

        storageService.completeMultipartUpload(session.getObjectKey(), session.getS3UploadId(), uploadedParts);
        // Save the session — PROCESSING, not COMPLETED: the multipart join is done, but the
        // file still needs to be transcoded into HLS before it's actually usable.
        session.setUpdatedAt(Instant.now());
        session.setStatus(UploadStatus.PROCESSING);
        repository.save(session);

        // Kick off the transcode asynchronously; the client polls getStatus() for READY/FAILED.
        transcodeService.transcode(sessionId);

        return new CompleteUploadResponse(sessionId, session.getObjectKey(), UploadStatus.PROCESSING);
    }

    @Override
    public void abortUpload(UUID sessionId) {
        UploadSession session = repository
                .findById(sessionId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Session with id " + sessionId + " doesn't exist")
                );
        if (session.getStatus() != UploadStatus.INITIATED && session.getStatus() != UploadStatus.UPLOADING) {
            throw new IllegalStateException("Cannot abort a session in status " + session.getStatus());
        }

        storageService.abortMultipartUpload(session.getObjectKey(), session.getS3UploadId());

        // Save the session
        session.setUpdatedAt(Instant.now());
        session.setStatus(UploadStatus.ABORTED);
        repository.save(session);

    }

    @Override
    @Scheduled(cron = "0 0 */6 * * *")
//    @Scheduled(cron = "0 * * * * *")
    public void cleanupStaleUploads() {
        // Only INITIATED/UPLOADING sessions can go stale — COMPLETED/ABORTED are already terminal.
        List<UploadStatus> statuses = List.of(UploadStatus.INITIATED, UploadStatus.UPLOADING);
        Instant cutoff = Instant.now().minus(Duration.ofHours(staleAfterHours));

        List<UploadSession> staleSessions = repository.findByStatusInAndUpdatedAtBefore(statuses, cutoff);
        log.info("Running cron ");
        if (staleSessions.isEmpty()) {
            return;
        }

        log.info("Found {} stale upload session(s) untouched since before {} — aborting.", staleSessions.size(), cutoff);

        for (UploadSession session : staleSessions) {
            try {
                abortUpload(session.getId());
                log.info("Aborted stale session {}", session.getId());
            } catch (Exception e) {
                // Don't let one bad session stop the rest of the cleanup run.
                log.warn("Failed to abort stale session {}: {}", session.getId(), e.getMessage());
            }
        }
    }

    private int calculateTotalParts(long fileSize) {
        // returns Ceil value
        return Math.toIntExact((fileSize + chunkSize - 1) / chunkSize);
    }
}