spring:
  application:
    name: Upload-Service


# Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/upload_service?createdDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 1


# Object Storage Configuration
minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket: videos
  chunk-size: 10485760 # 10 MB


# HLS Transcoding Configuration
transcode:
  ffmpeg-path: C:/Users/yogen/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-9.0.1-full_build/bin/ffmpeg.exe
  ffprobe-path: C:/Users/yogen/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-9.0.1-full_build/bin/ffprobe.exe
  work-dir: ${java.io.tmpdir}
  timeout-minutes: 120


server:
  port: 8080
